export const MOCK_SEQUENCE_DATA = [
  {
    id: 1,
    name: 'Sequence 1',
    color: 'indianred',
    phases: [
      {
        id: '1',
        name: 'Phase 1',
        badge: 'info',
        color: 'blue',
        time: '12:42',
      },
      {
        id: '2',
        name: 'Phase 2',
        badge: 'work',
        color: 'green',
        time: '12:42',
      },
      {
        id: '3',
        name: 'Phase 3',
        badge: 'info',
        color: 'red',
        time: '12:42',
      },
      {
        id: '4',
        name: 'Phase 4',
        badge: 'danger',
        color: 'blue',
        time: '12:42',
      },
      {
        id: '5',
        name: 'Phase 5',
        badge: 'danger',
        color: 'blue',
        time: '12:42',
      },
      {
        id: '6',
        name: 'Phase 6',
        badge: 'danger',
        color: 'blue',
        time: '12:42',
      },
    ],
  },
  {
    id: 2,
    name: 'Sequence 2',
    color: 'darkseagreen',
    phases: [
      {
        id: '1',
        name: 'Phase 1',
        badge: 'info',
        color: 'blue',
        time: '12:42',
      },
      {
        id: '2',
        name: 'Phase 2',
        badge: 'work',
        color: 'green',
        time: '12:42',
      },
      {
        id: '3',
        name: 'Phase 3',
        badge: 'info',
        color: 'red',
        time: '12:42',
      },
      {
        id: '4',
        name: 'Phase 4',
        badge: 'danger',
        color: 'blue',
        time: '12:42',
      },
    ],
  },
  {
    id: 3,
    name: 'Sequence 3',
    color: 'cornflowerblue',
    phases: [
      {
        id: '1',
        name: 'Phase 1',
        badge: 'info',
        color: 'blue',
        time: '02:42',
      },
      {
        id: '2',
        name: 'Phase 2',
        badge: 'work',
        color: 'green',
        time: '02:42',
      },
      {
        id: '3',
        name: 'Phase 3',
        badge: 'info',
        color: 'red',
        time: '02:42',
      },
      {
        id: '4',
        name: 'Phase 4',
        badge: 'danger',
        color: 'blue',
        time: '02:42',
      },
      {
        id: '5',
        name: 'Phase 5',
        badge: 'danger',
        color: 'blue',
        time: '02:42',
      },
      {
        id: '6',
        name: 'Phase 6',
        badge: 'danger',
        color: 'blue',
        time: '02:42',
      },
      {
        id: '7',
        name: 'Phase 7',
        badge: 'danger',
        color: 'blue',
        time: '02:42',
      },
      {
        id: '8',
        name: 'Phase 8',
        badge: 'danger',
        color: 'blue',
        time: '02:42',
      },
      {
        id: '9',
        name: 'Phase 9',
        badge: 'danger',
        color: 'blue',
        time: '02:42',
      },
    ],
  },
];